### ISSUE TITLE
Error using the Siebel REST API: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by ashokgithub85** [endoit/siebelScriptsEditor#10]

**Comment by lbakosendo** [comment]
Hi,

Please install a suitable certificate for Siebel.

Regards,
László

**Comment by Hucster** [comment]
In Windows you can add environment variable (User or System) for axios:
NODE_TLS_REJECT_UNAUTHORIZED = 0

Also, open chrome://settings/security in Chrome and add your siebel certificate to Trusted Publishers

Then restart VSCode. That's how I fixed this error
