### ISSUE TITLE
Methods are not getting imported into VSCode

### ISSUE THREAD

**Issue by ashipanw** [endoit/siebelScriptsEditor#11]
Hello Team,
We are trying to use the below extension. Upon successfully connecting to my developer workspace i am able to browse all the BO, BS etc. However i am not able to get any of the methods.
We tried both of the below given option after clicking on almost all BS , BO etc .
1. Yes
2. Only Methods Names
We cant see any methods getting imported. Kindly help.
Also we want to integrated this extension along with Co -pilot. Please suggest if both extension can work together to harness generative AI capabilities of co-pilot.

 Attaching screenshot.
<img width="324" alt="ss" src="https://github.com/endoit/siebelScriptsEditor/assets/93319203/4f5c75d1-18d1-4e43-b0fa-30dfd47fb156">

**Comment by lbakosendo** [comment]
Hi,

Does the Siebel objects have any server scripts? Because the extension only shows them in that case, methods without servers scripts are not shown.

About co-pilot integration, we have neither tested nor used co-pilot, but you can give it a try.

Regards,
László
