### ISSUE TITLE
Error using the Siebel REST API

### ISSUE THREAD

**Issue by bossuuu** [endoit/siebelScriptsEditor#8]
Any idea why i'm getting the following issue:
Error using the Siebel REST API: Error Creating XSD for Business Object <?>.(SBL-EAI-50238)

**Comment by lbakosendo** [comment]
Can you provide more information about the issue? Do you add the workspaces in the Workspaces setting manually, or is the Get Workspaces From REST setting enabled?

László

**Comment by bossuuu** [comment]
Workspace config was added manually.

Mike

**Comment by lbakosendo** [comment]
When does this error occur?

**Comment by bossuuu** [comment]
When I'm typing name of the object in search text field or when pressing reload.

M.

**Comment by lbakosendo** [comment]
What are your Settings for the extension?

Az Android Outlook<https://aka.ms/ghei36> letöltése
________________________________

**Comment by bossuuu** [comment]
![image](https://user-images.githubusercontent.com/114675416/194249516-708c961a-a91e-4352-b587-8ed079fbd362.png)

**Comment by lbakosendo** [comment]
The workspace given in the Default Connection does not exist in the Workspaces setting. Can you delete the Default Connection setting and see if it fixes the problem?



________________________________
Feladó: bossuuu ***@***.***>
Elküldve: 2022. október 6., csütörtök 9:53
Címzett: endoit/siebelScriptsEditor ***@***.***>
Másolat: Dr. Bakos László Péter ***@***.***>; Comment ***@***.***>
Tárgy: Re: [endoit/siebelScriptsEditor] Error using the Siebel REST API (Issue #8)


[image]<https://user-images.githubusercontent.com/114675416/194249516-708c961a-a91e-4352-b587-8ed079fbd362.png>

**Comment by lbakosendo** [comment]
Is there any development regarding this issue?

László
