### ISSUE TITLE
Connexion Error : Unable to verify firdt certificat

### ISSUE THREAD

**Issue by samamace** [endoit/siebelScriptsEditor#9]
Hi,
When I test my connexion, I have this error :
    "Error using the Siebel REST API: unable to verify the first certificate"

Our connexion is in https.
Could you add an option to set if we want or not check the certificate?
Regards

**Comment by lbakosendo** [comment]
Hi,

It is highly not recommended to the disable checking of the certificates, so we are not planning to implement it in the near future because of security reasons.

Regards,
László
